### ISSUE TITLE
banned from javdb

### ISSUE THREAD

**Issue by Freakboo** [javinizer/Javinizer#266]
Scraped too much at once?
Have dissabled in settings to remove.

Write-Error: C:\Users\Navi\Documents\PowerShell\Modules\Javinizer\2.4.11\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     | [MMZ-006] [Get-JavdbUrl] Error occured on [GET] on URL [https://javdb.com/search?q=MMZ-006&f=all]: The
     | owner of this website has banned your access based on your browser's behaving
IP: .*My IP*.

* Module version used: 2.4.11
* Operating System and PowerShell version: 10 x64, PS7 x64

**Comment by jvlflame** [comment]
Yep, some other users have also noted this. The ban seems to be a persistent (permanent?) IP ban from javdb unfortunately.
I'll probably have to remove/disable this scraper in further versions.

**Comment by jvlflame** [comment]
Heard from others that the unban was lifted after approximately 14 days. I'd caution anyone using this scraper to limit their sorting threads to ~1-2 at max.

**Comment by Borisbee1** [comment]
I was banned from javdb after I tried to scrape a single movie.  Could this issue be resolved by providing a user agent?

**Comment by jvlflame** [comment]
@Borisbee1 I'm not sure.. it's pretty hard to test javdb requests if their bans keep coming. They seem to have a pretty hard stance on scrapers so at this point I'm thinking of dropping support.

**Comment by aka-fork** [comment]
Please can you add the User-Agent when call to Javdb? Because Javdb has many results that other site doesn't have. :)

**Comment by gummykage** [comment]
I've tried setting the cookie, I've tried using VPN always get banned. Is there a way around this?

**Comment by local-develop** [comment]
@jvlflame You can use [stash](https://github.com/stashapp/stash) as reference.
https://github.com/stashapp/CommunityScrapers/blob/master/scrapers/javdb.yml

With cookie key: _jdb_session, remember_me_token and User-Agent used, I was not ban from javdb9.com

**Comment by aka-fork** [comment]
@jvlflame You can use [stash](https://github.com/stashapp/stash) as reference.
https://github.com/stashapp/CommunityScrapers/blob/master/scrapers/javdb.yml

With cookie key: _jdb_session, remember_me_token and User-Agent used, I was not ban from javdb9.com
