### ISSUE TITLE
An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by orophix** [javinizer/Javinizer#322]
## Expected Behavior
GUI installation

## Current Behavior
```
PS C:\Windows\System32> Javinizer -InstallGUI
Starting Javinizer GUI install...
Use the -Force parameter if you want to overwrite the existing PowerShell Universal install
Installing required modules...
Module [UniversalDashboard.Style] is already installed
Module [UniversalDashboard.UDPlayer] is already installed
Module [UniversalDashboard.UDSpinner] is already installed
Module [UniversalDashboard.UDScrollUp] is already installed
Module [UniversalDashboard.CodeEditor] is already installed
Installing PowerShell Universal...
Install-JVGui: C:\Users\pc\Documents\PowerShell\Modules\Javinizer\2.5.9\Public\Javinizer.ps1:659
Line |
 659 |                      Install-JVGui -Force:$Force
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error downloading and extracting PowerShell Universal: An attempt was made to access a socket in a way
     | forbidden by its access permissions.
```

I tried using -Force and I've tried this on a fresh Windows installation. 

## Steps to Reproduce (for bugs)
Javinizer -InstallGUI

## Your Environment
Name                           Value

PSVersion                 7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by jvlflame** [comment]
There's an issue with the download/extract of the PowerShell Universal archive.

https://github.com/jvlflame/Javinizer/blob/e5abb2e2654c44512d7553f26e283c3fb03bc975/src/Javinizer/Public/Install-JVGui.ps1#L17-L35

https://github.com/jvlflame/Javinizer/blob/e5abb2e2654c44512d7553f26e283c3fb03bc975/src/Javinizer/Public/Install-JVGui.ps1#L71-L81

Copy and run these 2 snippets in an admin PowerShell 7 window and see what it's erroring on.
