### ISSUE TITLE
Unable to connect to docker GUI

### ISSUE THREAD

**Issue by IACTA7** [javinizer/Javinizer#328]
## Current Behavior
I can't access into the GUI in Docker.
(Synology NAS user)

## Steps to Reproduce (for bugs)
The figure below shows my setup steps and current status.

1. I connected via ssh and installed the docker image. (Even after reinstalling 5 times, the same symptoms occur.)
![1](https://user-images.githubusercontent.com/100104048/154879319-041339df-8828-4f82-9966-021b47f4cff2.jpg)

2. These are the detailed settings in the container.
![image](https://user-images.githubusercontent.com/100104048/154879639-52d74220-864c-41c6-ae56-7a7084d06be3.png)
![image](https://user-images.githubusercontent.com/100104048/154879746-34ff5b15-d519-4b28-bdcd-85c500e8e181.png)
![image](https://user-images.githubusercontent.com/100104048/154879885-8598f9db-4ef4-4e64-834b-3eef55a1ae14.png)

3. I entered the dashboard and set it up as follows.
![image](https://user-images.githubusercontent.com/100104048/154880156-00e7929d-5ab3-4c24-aa0a-4479aa19804b.png)
![image](https://user-images.githubusercontent.com/100104048/154880199-f513a336-530e-48bd-8c0c-35dabffabc89.png)

4. I pasted the code copied from [here](https://github.com/jvlflame/Javinizer/blob/master/dashboard/main.ps1) in the blank space of the code part and saved it.
![image](https://user-images.githubusercontent.com/100104048/154880464-64e6688b-8c8e-4184-a8ed-b2ecdc81788d.png)

This is the log of that page.
![image](https://user-images.githubusercontent.com/100104048/154880590-5420ce59-d362-4601-9c55-ad3923d994c9.png)

5. After that, restart all and click 'view', an error occurs as shown below.
![image](https://user-images.githubusercontent.com/100104048/154880861-121c51b8-b5f4-4d43-a6e2-f2204cf45b1c.png)

I'd appreciate it if you could let me know if there is a solution.

## Your Environment
* Module version used: docker GUI: latest
* Operating System and PowerShell version: Synology DMS 7.0

**Comment by seeyabye** [comment]
I am not sure what you're trying to do. I am not too familiar with running dockers on proprietary NAS.

However, once you're able to run your docker container with `docker run ...`, all you need to do is open the browser accordingly. No need to mess with the dashboard settings.

Just access it with `http://your_nas_ip_address:8600` from your browser.

**Comment by seeyabye** [comment]
Please open a new issue if you're still facing this problem. Closing for now.
