### ISSUE TITLE
Using <FILENAME> as a tag for cover images doesn't copy over apostrophes

### ISSUE THREAD

**Issue by endofthescope** [javinizer/Javinizer#351]
EDIT: I'm using "FILENAME" as the tag only for illustrative purposes in this post, I'm using the correct tag in javinizer but github won't let me use the original tag because it must conflict with something. 

## Expected Behavior

When using "FILENAME"-fanart or "FILENAME"-poster as a tag for cover images, it should fully copy the video's filename.

## Current Behavior

It is skipping apostrophes

for example:

original video filename:

IPX-125 - Himawari Yuzuki, Ayumi Arihara - Beautifully Obscene Perverted Female Teacher Duo's After School Nympho Harem (2018-03-31).mkv

scraped cover filename after being renamed:

IPX-125 - Himawari Yuzuki, Ayumi Arihara - Beautifully Obscene Perverted Female Teacher Duos After School Nympho Harem (2018-03-31)-fanart.jpg

apostrophe is missing in the word "Duo's". This causes xbmcnfomoviesimporter to not find the poster and fanart for plex and requires manual intervention to fix. 

## Steps to Reproduce (for bugs)

Turn off video file renaming, scrape a video with an apostrophe in it's name, and set the tags in sort.format.thumbimg and sort.format.posterimg to "FILENAME"-fanart or "FILENAME"-poster respectively. The filenames before the dash won't perfectly match because they're missing apostrophes and won't be "caught" by some programs that use the pictures for presentation. I haven't found any other punctuation missing yet. 

I also don't want to change the filenames of my videos because I have them backed up and it'd be a real pain to change everything on my backup so it doesn't get uploaded twice by rclone. 

## Your Environment
* Module version used: 2.5.10
* Operating System and PowerShell version: windows 10 x64 powershell 7

**Comment by seeyabye** [comment]
I think apostrophe's should not be replaced as they are supposed to be valid on various file systems.

It should be resolved in the upcoming version 2.5.15. For now this has been pushed to master.
