### ISSUE TITLE
On GUI startup: WARNING: [Javinizer] Thumb csv not found at path [---]

### ISSUE THREAD

**Issue by kuroinu4991** [javinizer/Javinizer#360]
## Expected Behavior
To launch Javinizer GUI

## Current Behavior
Getting error
I have changed the Actress Thumbnail CSV location but now I cannot access the GUI to revert or do anything
## Your Environment
* Module version used:Latest
* Operating System and PowerShell version:

**Comment by seeyabye** [comment]
Have you checked if the latest version resolves your issue? Otherwise, could you please provide more information?
