### ISSUE TITLE
Write-Error with googletrans enabled

### ISSUE THREAD

**Issue by zuko7177** [javinizer/Javinizer#376]
I'm getting the following errors when enabling Googletrans.  This is intermittent.  I'm guessing it happens 30% on average. On a batch of 10 files to process, I may get 3 of the files with this error.  If I rerun Javinizer with those same three files, it would work ok.

Here's the errors:
PS C:\Users\bobby> Javinizer
Write-Error: C:\Users\bobby\Documents\PowerShell\Modules\Javinizer\2.5.17\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     | Traceback (most recent call last):
Write-Error: C:\Users\bobby\Documents\PowerShell\Modules\Javinizer\2.5.17\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     |   File "C:\Users\bobby\Documents\PowerShell\Modules\Javinizer\2.5.17\translate.py", line 7, in <module>
Write-Error: C:\Users\bobby\Documents\PowerShell\Modules\Javinizer\2.5.17\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     |     translation = translator.translate(sys.argv[1], dest=sys.argv[2])
Write-Error: C:\Users\bobby\Documents\PowerShell\Modules\Javinizer\2.5.17\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Write-Error: C:\Users\bobby\Documents\PowerShell\Modules\Javinizer\2.5.17\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     |   File "C:\Users\bobby\AppData\Local\Programs\Python\Python311\Lib\site-packages\googletrans\client.py", line
     | 219, in translate
Write-Error: C:\Users\bobby\Documents\PowerShell\Modules\Javinizer\2.5.17\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     |     parsed = json.loads(data[0][2])
Write-Error: C:\Users\bobby\Documents\PowerShell\Modules\Javinizer\2.5.17\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     |              ^^^^^^^^^^^^^^^^^^^^^^
Write-Error: C:\Users\bobby\Documents\PowerShell\Modules\Javinizer\2.5.17\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     |   File "C:\Users\bobby\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 339, in loads
Write-Error: C:\Users\bobby\Documents\PowerShell\Modules\Javinizer\2.5.17\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     |     raise TypeError(f'the JSON object must be str, bytes or bytearray, '
Write-Error: C:\Users\bobby\Documents\PowerShell\Modules\Javinizer\2.5.17\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     | TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Write-Error: C:\Users\bobby\Documents\PowerShell\Modules\Javinizer\2.5.17\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.
Write-Error: C:\Users\bobby\Documents\PowerShell\Modules\Javinizer\2.5.17\Public\Invoke-JVParallel.ps1:561
Line |
 561 |                      Get-RunspaceData
     |                      ~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.

Here's my jvSettings:

  "sort.metadata.nfo.translate": true,
  "sort.metadata.nfo.translate.module": "googletrans",
  "sort.metadata.nfo.translate.field": "description",
  "sort.metadata.nfo.translate.language": "en",
  "sort.metadata.nfo.translate.deeplapikey": "",
  "sort.metadata.nfo.translate.keeporiginaldescription": false,

Version used: 2.5.17.  

Thanks.

**Comment by seeyabye** [comment]
With a batch of 10, you will easily hit Google Translate's anti-bot.
Also I'm not sure how many fields are you currently trying to translate. If you multiply that with the number of concurrent batches, it will definitely trigger the alarm.

This is unfortunately not an issue with Javinizer and cannot be fixed.
